#!/usr/bin/env python3
"""Manage the Proxmox node fleet from a single inventory file.

`proxmox-config/nodes.json` is the source of truth. Everything else --
the per-node MCP configs, docker-compose.yml, and .mcp.json -- is generated
from it by `sync`, so adding or removing a node is a one-command change.

    ./scripts/nodes.py list                 show the fleet
    ./scripts/nodes.py test                 auth-check every node over the API
    ./scripts/nodes.py add   --name nodeF --host 192.168.8.20 \
                             --token-name nodeF --token-value <uuid>
    ./scripts/nodes.py remove --name nodeF
    ./scripts/nodes.py sync                 regenerate all derived files

Stdlib only -- no virtualenv needed to run it.
"""
from __future__ import annotations

import argparse
import json
import os
import ssl
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INVENTORY = ROOT / "proxmox-config" / "nodes.json"
CONFIG_DIR = ROOT / "proxmox-config"
COMPOSE = ROOT / "docker-compose.yml"
MCP_JSON = ROOT / ".mcp.json"

CONTAINER_PORT = 8811
GENERATED = "# GENERATED by scripts/nodes.py -- edit proxmox-config/nodes.json instead.\n"


# --------------------------------------------------------------------------- io


def load() -> dict:
    if not INVENTORY.exists():
        sys.exit(f"missing inventory: {INVENTORY}")
    return json.loads(INVENTORY.read_text())


def save(inv: dict) -> None:
    # Keep a stable order so add/remove churn doesn't reshuffle generated files.
    inv["nodes"] = sorted(inv.get("nodes", []), key=lambda n: n["name"])
    INVENTORY.write_text(json.dumps(inv, indent=2) + "\n")
    INVENTORY.chmod(0o600)


def nodes_of(inv: dict) -> list[dict]:
    return inv.get("nodes", [])


# --------------------------------------------------------------------- generate


def write_node_configs(inv: dict) -> list[Path]:
    """One MCP config per node. Returns the files it wrote."""
    d = inv.get("defaults", {})
    written = []
    for n in nodes_of(inv):
        cfg = {
            "proxmox": {
                "host": n["host"],
                "port": n.get("port", d.get("port", 8006)),
                "verify_ssl": n.get("verify_ssl", d.get("verify_ssl", False)),
                "service": "PVE",
            },
            "auth": {
                "user": n.get("user", d.get("user", "root@pam")),
                "token_name": n["token_name"],
                "token_value": n["token_value"],
            },
            "logging": {
                "level": n.get("log_level", d.get("log_level", "INFO")),
                "format": f"%(asctime)s - {n['name']} - %(name)s - %(levelname)s - %(message)s",
            },
        }
        p = CONFIG_DIR / f"config.{n['name']}.json"
        p.write_text(json.dumps(cfg, indent=2) + "\n")
        p.chmod(0o600)
        written.append(p)
    return written


def prune_stale_configs(inv: dict, keep: list[Path]) -> list[Path]:
    """Delete config.<node>.json files for nodes no longer in the inventory."""
    keep_names = {p.name for p in keep}
    removed = []
    for p in sorted(CONFIG_DIR.glob("config.*.json")):
        if p.name == "config.example.json" or p.name in keep_names:
            continue
        p.unlink()
        removed.append(p)
    return removed


def write_compose(inv: dict) -> None:
    lines = [
        GENERATED,
        "# Each node is a standalone Proxmox host, so it gets its own instance:\n",
        "# the config schema holds exactly one host + one token.\n",
        "\n",
        "x-node-common: &node-common\n",
        "  build: .\n",
        "  image: proxmox-mcp-plus:latest\n",
        "  volumes:\n",
        "    - ./proxmox-config:/app/proxmox-config:ro\n",
        "  restart: unless-stopped\n",
        "  networks:\n",
        "    - proxmox-network\n",
        "\n",
        "services:\n",
    ]
    for n in nodes_of(inv):
        name, port = n["name"], n["http_port"]
        lines += [
            f"  {name}:\n",
            "    <<: *node-common\n",
            f"    container_name: proxmox-mcp-{name}\n",
            f"    # {n['host']} -> http://localhost:{port}\n",
            "    ports:\n",
            f'      - "{port}:{CONTAINER_PORT}"\n',
            "    environment:\n",
            f"      - PROXMOX_MCP_CONFIG=/app/proxmox-config/config.{name}.json\n",
            "      - API_HOST=0.0.0.0\n",
            f"      - API_PORT={CONTAINER_PORT}\n",
            "    healthcheck:\n",
            f'      test: ["CMD", "curl", "-f", "http://localhost:{CONTAINER_PORT}/openapi.json"]\n',
            "      interval: 30s\n",
            "      timeout: 10s\n",
            "      retries: 3\n",
            "      start_period: 20s\n",
            "\n",
        ]
    lines += ["networks:\n", "  proxmox-network:\n", "    driver: bridge\n"]
    COMPOSE.write_text("".join(lines))


def write_mcp_json(inv: dict) -> None:
    """Register each node as its own MCP server so they can be addressed one at a time.

    Each entry attaches to that node's already-running container over stdio, so
    `docker compose up -d` must have been run first.
    """
    servers = {
        f"proxmox-{n['name']}": {
            "command": "docker",
            "args": [
                "exec", "-i", f"proxmox-mcp-{n['name']}",
                "/bin/bash", "-c",
                "cd /app && source .venv/bin/activate && python -m proxmox_mcp.server",
            ],
        }
        for n in nodes_of(inv)
    }
    MCP_JSON.write_text(json.dumps({"mcpServers": servers}, indent=2) + "\n")


# ------------------------------------------------------------------- api probe


def probe(node: dict, defaults: dict, timeout: float = 8.0) -> str:
    """Hit /version with the node's token. Returns a human-readable status."""
    user = node.get("user", defaults.get("user", "root@pam"))
    port = node.get("port", defaults.get("port", 8006))
    url = f"https://{node['host']}:{port}/api2/json/version"
    token = f"PVEAPIToken={user}!{node['token_name']}={node['token_value']}"
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    req = urllib.request.Request(url, headers={"Authorization": token})
    try:
        with urllib.request.urlopen(req, timeout=timeout, context=ctx) as r:
            data = json.loads(r.read())["data"]
            return f"OK    pve {data['version']}"
    except urllib.error.HTTPError as e:
        hint = "  (check token name/secret)" if e.code == 401 else ""
        return f"AUTH  HTTP {e.code}{hint}"
    except Exception as e:  # unreachable, TLS failure, timeout
        return f"DOWN  {type(e).__name__}: {str(e)[:60]}"


# ---------------------------------------------------------------------- actions


def cmd_list(args) -> None:
    inv = load()
    ns = nodes_of(inv)
    print(f"{'NODE':<8} {'PROXMOX HOST':<22} {'TOKEN':<22} {'URL':<26} CONTAINER")
    for n in ns:
        user = n.get("user", inv["defaults"].get("user", "root@pam"))
        print(
            f"{n['name']:<8} {n['host'] + ':' + str(n.get('port', 8006)):<22} "
            f"{user + '!' + n['token_name']:<22} "
            f"{'http://localhost:' + str(n['http_port']):<26} proxmox-mcp-{n['name']}"
        )
    print(f"\n{len(ns)} node(s).")


def cmd_test(args) -> None:
    inv = load()
    d = inv.get("defaults", {})
    bad = 0
    for n in nodes_of(inv):
        status = probe(n, d)
        print(f"{n['name']:<8} {n['host']:<16} {status}")
        if not status.startswith("OK"):
            bad += 1
    sys.exit(1 if bad else 0)


def cmd_add(args) -> None:
    inv = load()
    ns = nodes_of(inv)
    if any(n["name"] == args.name for n in ns):
        sys.exit(f"node '{args.name}' already exists -- remove it first or pick another name")

    port = args.http_port
    if port is None:
        used = {n["http_port"] for n in ns}
        port = max(used, default=8810) + 1
        while port in used:
            port += 1
    if any(n["http_port"] == port for n in ns):
        sys.exit(f"http port {port} already used")

    node = {
        "name": args.name,
        "host": args.host,
        "token_name": args.token_name,
        "token_value": args.token_value,
        "http_port": port,
    }
    if args.user:
        node["user"] = args.user

    status = probe(node, inv.get("defaults", {}))
    print(f"probe {args.host}: {status}")
    if not status.startswith("OK") and not args.force:
        sys.exit("refusing to add an unreachable node (use --force to add anyway)")

    ns.append(node)
    save(inv)
    print(f"added {args.name} -> http://localhost:{port}")
    _sync(inv)


def cmd_remove(args) -> None:
    inv = load()
    ns = nodes_of(inv)
    match = [n for n in ns if n["name"] == args.name]
    if not match:
        sys.exit(f"no such node: {args.name}")
    inv["nodes"] = [n for n in ns if n["name"] != args.name]
    save(inv)
    print(f"removed {args.name}")
    _sync(inv)
    print(f"\nnow run:  docker compose up -d --remove-orphans")
    print(f"          (stops and deletes container proxmox-mcp-{args.name})")


def _sync(inv: dict) -> None:
    written = write_node_configs(inv)
    removed = prune_stale_configs(inv, written)
    write_compose(inv)
    write_mcp_json(inv)
    for p in written:
        print(f"  config  {p.relative_to(ROOT)}")
    for p in removed:
        print(f"  deleted {p.relative_to(ROOT)}")
    print(f"  compose {COMPOSE.relative_to(ROOT)}")
    print(f"  mcp     {MCP_JSON.relative_to(ROOT)}")


def cmd_sync(args) -> None:
    _sync(load())
    print("\nnow run:  docker compose up -d --remove-orphans")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="show the fleet").set_defaults(func=cmd_list)
    sub.add_parser("test", help="auth-check every node").set_defaults(func=cmd_test)
    sub.add_parser("sync", help="regenerate configs, compose, .mcp.json").set_defaults(func=cmd_sync)

    a = sub.add_parser("add", help="add a node")
    a.add_argument("--name", required=True)
    a.add_argument("--host", required=True)
    a.add_argument("--token-name", required=True)
    a.add_argument("--token-value", required=True)
    a.add_argument("--user", help="default: root@pam")
    a.add_argument("--http-port", type=int, help="default: next free port")
    a.add_argument("--force", action="store_true", help="add even if unreachable")
    a.set_defaults(func=cmd_add)

    r = sub.add_parser("remove", help="remove a node")
    r.add_argument("--name", required=True)
    r.set_defaults(func=cmd_remove)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
