#!/usr/bin/env python3
"""Manage Proxmox cluster connections from a single inventory file.

`proxmox-config/nodes.json` is the source of truth. Everything else --
the combined MCP config, docker-compose.yml, and .mcp.json -- is generated
from it by `sync`, so adding or removing a cluster is a one-command change.

    ./scripts/nodes.py list                 show configured clusters
    ./scripts/nodes.py test                 auth-check every cluster over the API
    ./scripts/nodes.py add   --name guild-b --host 192.168.9.20 \
                             --token-name nodeF --token-value <uuid>
    ./scripts/nodes.py remove --name guild-b
    ./scripts/nodes.py sync                 regenerate all derived files

Stdlib only -- no virtualenv needed to run it.
"""
from __future__ import annotations

import argparse
import json
import os
import ssl
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INVENTORY = ROOT / "proxmox-config" / "nodes.json"
CONFIG_DIR = ROOT / "proxmox-config"
COMPOSE = ROOT / "docker-compose.yml"
MCP_JSON = ROOT / ".mcp.json"
ENV_FILE = ROOT / ".env"

CONTAINER_PORT = 8811
DEFAULT_SERVICE = "guild-a"
GENERATED = "# GENERATED by scripts/nodes.py -- edit proxmox-config/nodes.json instead.\n"


# --------------------------------------------------------------------------- io


def load() -> dict:
    if not INVENTORY.exists():
        sys.exit(f"missing inventory: {INVENTORY}")
    return json.loads(INVENTORY.read_text())


def save(inv: dict) -> None:
    # Keep a stable order so add/remove churn doesn't reshuffle generated files.
    inv["nodes"] = sorted(inv.get("nodes", []), key=lambda n: n["name"])
    INVENTORY.write_text(json.dumps(inv, indent=2) + "\n")
    INVENTORY.chmod(0o600)


def env_key(name: str) -> str:
    safe = "".join(c if c.isalnum() else "_" for c in name.upper())
    return f"PROXMOX_MCP_TOKEN_{safe}"


def load_env_file() -> dict[str, str]:
    env = {}
    if not ENV_FILE.exists():
        return env
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        env[key.strip()] = value.strip().strip('"').strip("'")
    return env


def write_env_file(values: dict[str, str]) -> None:
    current = load_env_file()
    current.update(values)
    body = "\n".join(f"{key}={current[key]}" for key in sorted(current)) + "\n"
    ENV_FILE.write_text(body)
    ENV_FILE.chmod(0o600)


def load_env_into_process() -> None:
    for key, value in load_env_file().items():
        os.environ.setdefault(key, value)


def token_value(node: dict) -> str:
    if node.get("token_value"):
        return node["token_value"]
    token_env = node.get("token_env")
    if not token_env:
        raise KeyError(f"{node['name']} has no token_value or token_env")
    value = os.getenv(token_env)
    if value is None:
        raise KeyError(f"{node['name']} token env var is not set: {token_env}")
    return value


def token_ref(node: dict) -> str:
    if node.get("token_env"):
        return "${" + node["token_env"] + "}"
    return node["token_value"]


def nodes_of(inv: dict) -> list[dict]:
    return inv.get("nodes", [])


def default_node(inv: dict) -> dict:
    ns = nodes_of(inv)
    if not ns:
        sys.exit("inventory has no clusters")
    default = inv.get("default_cluster") or ns[0]["name"]
    for n in ns:
        if n["name"] == default:
            return n
    sys.exit(f"default_cluster '{default}' is not in inventory")


# --------------------------------------------------------------------- generate


def write_node_configs(inv: dict) -> list[Path]:
    """One combined MCP config containing every configured cluster."""
    d = inv.get("defaults", {})
    default = default_node(inv)
    clusters = []
    for n in nodes_of(inv):
        clusters.append({
            "name": n["name"],
            "proxmox": {
                "host": n["host"],
                "port": n.get("port", d.get("port", 8006)),
                "verify_ssl": n.get("verify_ssl", d.get("verify_ssl", False)),
                "service": "PVE",
            },
            "auth": {
                "user": n.get("user", d.get("user", "root@pam")),
                "token_name": n["token_name"],
                "token_value": token_ref(n),
            },
        })
    default_cluster = next(c for c in clusters if c["name"] == default["name"])
    cfg = {
        "default_cluster": default["name"],
        "proxmox": default_cluster["proxmox"],
        "auth": default_cluster["auth"],
        "clusters": clusters,
        "logging": {
            "level": default.get("log_level", d.get("log_level", "INFO")),
            "format": "%(asctime)s - multi-cluster - %(name)s - %(levelname)s - %(message)s",
        },
    }
    p = CONFIG_DIR / f"config.{default['name']}.json"
    p.write_text(json.dumps(cfg, indent=2) + "\n")
    p.chmod(0o600)
    return [p]
    return written


def prune_stale_configs(inv: dict, keep: list[Path]) -> list[Path]:
    """Delete config.<node>.json files for nodes no longer in the inventory."""
    keep_names = {p.name for p in keep}
    removed = []
    for p in sorted(CONFIG_DIR.glob("config.*.json")):
        if p.name == "config.example.json" or p.name in keep_names:
            continue
        p.unlink()
        removed.append(p)
    return removed


def write_compose(inv: dict) -> None:
    default = default_node(inv)
    name, port = default["name"], default["http_port"]
    lines = [
        GENERATED,
        "# One MCP process can route pve_call to multiple Proxmox clusters.\n",
        "\n",
        "x-node-common: &node-common\n",
        "  build: .\n",
        "  image: proxmox-mcp-plus:latest\n",
        "  env_file:\n",
        "    - ./.env\n",
        "  volumes:\n",
        "    - ./proxmox-config:/app/proxmox-config:ro\n",
        "  restart: unless-stopped\n",
        "  networks:\n",
        "    - proxmox-network\n",
        "\n",
        "services:\n",
        f"  {name}:\n",
        "    <<: *node-common\n",
        f"    container_name: proxmox-mcp-{name}\n",
        f"    # multi-cluster MCP -> http://localhost:{port}\n",
        "    ports:\n",
        f'      - "${{PROXMOX_MCP_BIND_HOST:-0.0.0.0}}:{port}:{CONTAINER_PORT}"\n',
        "    environment:\n",
        f"      - PROXMOX_MCP_CONFIG=/app/proxmox-config/config.{name}.json\n",
        "      - API_HOST=0.0.0.0\n",
        f"      - API_PORT={CONTAINER_PORT}\n",
        "    healthcheck:\n",
        f'      test: ["CMD", "curl", "-f", "http://localhost:{CONTAINER_PORT}/openapi.json"]\n',
        "      interval: 30s\n",
        "      timeout: 10s\n",
        "      retries: 3\n",
        "      start_period: 20s\n",
        "\n",
    ]
    lines += ["networks:\n", "  proxmox-network:\n", "    driver: bridge\n"]
    COMPOSE.write_text("".join(lines))


def write_mcp_json(inv: dict) -> None:
    """Register the combined multi-cluster MCP server.

    The entry attaches to the already-running container over stdio, so
    `docker compose up -d` must have been run first.
    """
    name = default_node(inv)["name"]
    servers = {
        f"proxmox-{name}": {
            "command": "docker",
            "args": [
                "exec", "-i", f"proxmox-mcp-{name}",
                "/bin/bash", "-c",
                "cd /app && source .venv/bin/activate && python -m proxmox_mcp.server",
            ],
        }
    }
    MCP_JSON.write_text(json.dumps({"mcpServers": servers}, indent=2) + "\n")


# ------------------------------------------------------------------- api probe


def probe(node: dict, defaults: dict, timeout: float = 8.0) -> str:
    """Hit /version with the node's token. Returns a human-readable status."""
    user = node.get("user", defaults.get("user", "root@pam"))
    port = node.get("port", defaults.get("port", 8006))
    url = f"https://{node['host']}:{port}/api2/json/version"
    try:
        secret = token_value(node)
    except KeyError as e:
        return f"ENV   {e}"
    token = f"PVEAPIToken={user}!{node['token_name']}={secret}"
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    req = urllib.request.Request(url, headers={"Authorization": token})
    try:
        with urllib.request.urlopen(req, timeout=timeout, context=ctx) as r:
            data = json.loads(r.read())["data"]
            return f"OK    pve {data['version']}"
    except urllib.error.HTTPError as e:
        hint = "  (check token name/secret)" if e.code == 401 else ""
        return f"AUTH  HTTP {e.code}{hint}"
    except Exception as e:  # unreachable, TLS failure, timeout
        return f"DOWN  {type(e).__name__}: {str(e)[:60]}"


# ---------------------------------------------------------------------- actions


def cmd_list(args) -> None:
    inv = load()
    ns = nodes_of(inv)
    print(f"{'NODE':<8} {'PROXMOX HOST':<22} {'TOKEN':<22} {'SECRET':<28} {'URL':<26} CONTAINER")
    for n in ns:
        user = n.get("user", inv["defaults"].get("user", "root@pam"))
        secret = n.get("token_env", "inline token_value")
        print(
            f"{n['name']:<8} {n['host'] + ':' + str(n.get('port', 8006)):<22} "
            f"{user + '!' + n['token_name']:<22} "
            f"{secret:<28} "
            f"{'http://localhost:' + str(n['http_port']):<26} proxmox-mcp-{n['name']}"
        )
    print(f"\n{len(ns)} cluster(s).")


def cmd_test(args) -> None:
    load_env_into_process()
    inv = load()
    d = inv.get("defaults", {})
    bad = 0
    for n in nodes_of(inv):
        status = probe(n, d)
        print(f"{n['name']:<8} {n['host']:<16} {status}")
        if not status.startswith("OK"):
            bad += 1
    sys.exit(1 if bad else 0)


def cmd_add(args) -> None:
    load_env_into_process()
    inv = load()
    ns = nodes_of(inv)
    if any(n["name"] == args.name for n in ns):
        sys.exit(f"node '{args.name}' already exists -- remove it first or pick another name")

    port = args.http_port
    if port is None:
        used = {n["http_port"] for n in ns}
        port = max(used, default=8810) + 1
        while port in used:
            port += 1
    if any(n["http_port"] == port for n in ns):
        sys.exit(f"http port {port} already used")

    token_env = args.token_env or env_key(args.name)
    write_env_file({token_env: args.token_value})
    os.environ[token_env] = args.token_value

    node = {
        "name": args.name,
        "host": args.host,
        "token_name": args.token_name,
        "token_env": token_env,
        "http_port": port,
    }
    if args.user:
        node["user"] = args.user

    status = probe(node, inv.get("defaults", {}))
    print(f"probe {args.host}: {status}")
    if not status.startswith("OK") and not args.force:
        sys.exit("refusing to add an unreachable node (use --force to add anyway)")

    ns.append(node)
    save(inv)
    print(f"added {args.name} -> http://localhost:{port}")
    _sync(inv)


def cmd_remove(args) -> None:
    inv = load()
    ns = nodes_of(inv)
    match = [n for n in ns if n["name"] == args.name]
    if not match:
        sys.exit(f"no such node: {args.name}")
    inv["nodes"] = [n for n in ns if n["name"] != args.name]
    save(inv)
    print(f"removed {args.name}")
    _sync(inv)
    print(f"\nnow run:  docker compose up -d --remove-orphans")
    print(f"          (stops and deletes container proxmox-mcp-{args.name})")


def _sync(inv: dict) -> None:
    written = write_node_configs(inv)
    removed = prune_stale_configs(inv, written)
    write_compose(inv)
    write_mcp_json(inv)
    for p in written:
        print(f"  config  {p.relative_to(ROOT)}")
    for p in removed:
        print(f"  deleted {p.relative_to(ROOT)}")
    print(f"  compose {COMPOSE.relative_to(ROOT)}")
    print(f"  mcp     {MCP_JSON.relative_to(ROOT)}")


def cmd_sync(args) -> None:
    _sync(load())
    print("\nnow run:  docker compose up -d --remove-orphans")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="show configured clusters").set_defaults(func=cmd_list)
    sub.add_parser("test", help="auth-check every cluster").set_defaults(func=cmd_test)
    sub.add_parser("sync", help="regenerate configs, compose, .mcp.json").set_defaults(func=cmd_sync)

    a = sub.add_parser("add", help="add a cluster")
    a.add_argument("--name", required=True)
    a.add_argument("--host", required=True)
    a.add_argument("--token-name", required=True)
    a.add_argument("--token-value", required=True)
    a.add_argument("--token-env", help="default: PROXMOX_MCP_TOKEN_<NAME>")
    a.add_argument("--user", help="default: root@pam")
    a.add_argument("--http-port", type=int, help="default: next free port")
    a.add_argument("--force", action="store_true", help="add even if unreachable")
    a.set_defaults(func=cmd_add)

    r = sub.add_parser("remove", help="remove a cluster")
    r.add_argument("--name", required=True)
    r.set_defaults(func=cmd_remove)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
